In [46]:
# Import Supporting Libraries
from sklearn import datasets
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report, confusion_matrix
import pickle
import requests
import json
import os
# import pandas as pd
# from requests.auth import HTTPProxyAuth

In [47]:
# Load iris dataset
iris = datasets.load_iris()

In [48]:
# Print iris description 
print(iris.DESCR)

Iris Plants Database

Notes
-----
Data Set Characteristics:
    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20  0.76     0.9565  (high!)
    ============== ==== ==== ======= ===== ====================

    :Missing Attribute Values: None
  

In [49]:
# Assign independent features "data" to X and dependent feature "target" to y
X = iris.data
y = iris.target

In [50]:
# Print target names
print(iris['target_names'])

['setosa' 'versicolor' 'virginica']


In [51]:
# Print Iris array X-variables, indepedent features
print(iris.data)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.1 1.5 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [52]:
print(type(iris.data))

<class 'numpy.ndarray'>


In [53]:
# Print Iris array Y-variable, dependent feature
print(iris.target)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [66]:
# Perform train, test split with 70% X_train, X_test, y_train, y_test
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3)

In [67]:
# Instantiate Random Forest Classifier with 100 n_estimators and 2 n_jobs
rfc = RandomForestClassifier(n_estimators = 200, n_jobs = 4)

In [68]:
# Fit Random Forest Classifier
rfc.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=200, n_jobs=4,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [69]:
# Print accuracy score
# Print classification report
print("Accuracy = %0.2f" % accuracy_score (y_test, rfc.predict(X_test)))
print(classification_report(y_test, rfc.predict(X_test)))

Accuracy = 0.96
             precision    recall  f1-score   support

          0       1.00      1.00      1.00        12
          1       0.95      0.95      0.95        21
          2       0.92      0.92      0.92        12

avg / total       0.96      0.96      0.96        45



In [70]:
# Generate predicted values (y_pred)
y_pred = rfc.predict(X_test)

## Model Serialization

In [71]:
# Pickle dump rfc model
pickle.dump(rfc, open("iris_rfc.pkl", "wb"))

In [72]:
# Pickle load rfc model
my_random_forest = pickle.load(open("iris_rfc.pkl", 'rb'))

In [73]:
# View Random Forest
my_random_forest

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=200, n_jobs=4,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [74]:
# Print classification report again
print(classification_report(y_test, y_pred))

             precision    recall  f1-score   support

          0       1.00      1.00      1.00        12
          1       0.95      0.95      0.95        21
          2       0.92      0.92      0.92        12

avg / total       0.96      0.96      0.96        45



### Flask web dev endpoint!

In [134]:
# Set the environment variable NO_PROXY for localhost if behind proxy
os.environ['NO_PROXY'] = '127.0.0.1'
url = "http://127.0.0.1:9000/ml_api"
versicolor_data = json.dumps({'sl':5.24,'sw':3.0,'pl':3.75,'pw':1.1})
r = requests.post(url, versicolor_data)
print(r.json())

{'results': {'y_hat': '[1]'}}


In [135]:
# Set the environment variable NO_PROXY for localhost if behind proxy
os.environ['NO_PROXY'] = '127.0.0.1'
url = "http://127.0.0.1:9000/ml_api"
mix_data = json.dumps({'sl':[5.24,6.1],'sw':[3.0,3.4],'pl':[3.75,5.6],'pw':[1.1,2.1]})
r = requests.post(url, mix_data)
print(r.json())

{'results': {'y_hat': '[1, 2]'}}


In [136]:
# Set the environment variable NO_PROXY for localhost if behind proxy
os.environ['NO_PROXY'] = '127.0.0.1'
url = "http://127.0.0.1:9000/ml_api"
virginica_data = json.dumps({'sl':6.1,'sw':3.4,'pl':5.6,'pw':2.1})
r = requests.post(url, virginica_data)
print(r.json())

{'results': {'y_hat': '[2]'}}
